### ISSUE TITLE
Gagal check out

### ISSUE THREAD

**Issue by marwanto13** [bro-11/flasher2#9]
Help

**Comment by bro-11** [comment]
sebentar ane ambil menyan dulu

**Comment by bro-11** [comment]
duh lupa mantra lagi

**Comment by bro-11** [comment]
sedang di fix bugnya
![dukun.jpg](https://assets-a1.kompasiana.com/items/album/2020/12/26/images-5fe689848ede485e9a655452.jpeg)

**Comment by marwanto13** [comment]
Kopinya jangan lupa 😀😀😀

**Comment by marwanto13** [comment]
Mbah trawangin gua dong kok gk dapat flashsale terus nih
Kenapa yaaa😴😴😴
